ingestion_configs:
    api_type:
#        betting:
#            api_class:
#                name: BettingApi
#                api_methods:
#                    get_lines:
#                        filter_config:
#                            game_id:
#                            year:
#                            week:
#                            season_type:
#                            team:
#                            home:
#                            away:
#                            conference:
#        coaches:
#            api_class:
#                name: CoachesApi
#                api_methods:
#                    get_coaches:
#                        filter_config:
#                            first_name:
#                            last_name:
#                            team:
#                            year: 2022
#                            min_year:
#                            max_year:
#        conferences:
#           api_class:
#               name: ConferencesApi
#               api_methods:
#                    get_conferences:
#                        filter_config:
#        games:
#            api_class:
#                name: GamesApi
#                api_methods:
#                    #get_advanced_box_score - pending code fix for support:
#                    #    filter_config:
#                    #        game_id: 401415230
#                    get_calendar:
#                        filter_config:
#                            year: 2022
#                    get_game_media:
#                        filter_config:
#                            year: 2022
#                            week:
#                            season_type:
#                            team:
#                            conference:
#                            media_type:
#                            classification:
#                    #get_game_weather - Requires Patreon subscription to use:
#                    #    filter_config:
#                    #        game_id:
#                    #        year: 2022
#                    #        week:
#                    #        season_type:
#                    #        team:
#                    #        conference:
#                    #        classification:
#                    get_games:
#                        filter_config:
#                            year: 2022
#                            week:
#                            season_type:
#                            team:
#                            home:
#                            away:
#                            conference:
#                            division:
#                            id:
#                    get_player_game_stats:
#                        filter_config:
#                            year: 2022
#                            week:
#                            season_type:
#                            team: Wyoming
#                            conference:
#                            category:
#                            game_id:
#                    #get_scoreboard - Requires Patreon subscription to use:
#                    #    filter_config:
#                    #        classification:
#                    #        conference:
#                    get_team_game_stats:
#                        filter_config:
#                            year: 2022
#                            week:
#                            season_type:
#                            team: Wyoming
#                            conference:
#                            game_id:
#                            classification:
#                    get_team_records:
#                        filter_config:
#                            year: 2022
#                            team:
#                            conference:
#        metrics:
#            api_class:
#                name: MetricsApi
#                api_methods:
#                    get_game_ppa:
#                        filter_config:
#                            year: 2022
#                            week:
#                            team: Wyoming
#                            conference:
#                            exclude_garbage_time:
#                            season_type:
#                    get_player_game_ppa:
#                        filter_config:
#                            year: 2022
#                            week:
#                            team: Wyoming
#                            position:
#                            player_id:
#                            threshold:
#                            exclude_garbage_time:
#                            season_type:
#                    get_player_season_ppa:
#                        filter_config:
#                            year: 2022
#                            team: Wyoming
#                            conference:
#                            position:
#                            player_id:
#                            threshold:
#                            exclude_garbage_time:
#                    get_predicted_points:
#                        filter_config:
#                            down: 3
#                            distance: 10
#                    get_pregame_win_probabilities:
#                        filter_config:
#                            year: 2022
#                            week:
#                            team: Wyoming
#                            season_type:
#                    get_team_ppa:
#                        filter_config:
#                            year: 2022
#                            team: Wyoming
#                            conference:
#                            exclude_garbage_time:
#                    get_win_probability_data:
#                        filter_config:
#                            game_id: 401415230
#        players:
#            api_class:
#                name: PlayersApi
#                api_methods:
#                    get_player_season_stats:
#                        filter_config:
#                            year: 2022
#                            team: Wyoming
#                            conference:
#                            start_week:
#                            end_week:
#                            season_type:
#                            category:
#                    get_player_usage:
#                        filter_config:
#                            year: 2022
#                            team: Wyoming
#                            conference:
#                            position:
#                            player_id:
#                            exclude_garbage_time:
#                    get_returning_production:
#                        filter_config:
#                            year: 2022
#                            team: Wyoming
#                            conference:
#                    get_transfer_portal:
#                        filter_config:
#                            year: 2022
#                    #player_search - open ended search, skipping for now:
#                    #    filter_config:
#                    #        search_term: fast
#                    #        position:
#                    #        team: Wyoming
#                    #        year: 2022
#        plays:
#            api_class:
#                name: PlaysApi
#                api_methods:
#                    #get_live_plays - requires patreon subscription
#                    #    filter_config:
#                    #        id: 401415230
#                    get_play_stat_types:
#                        filter_config:
#                    get_play_stats:
#                        filter_config:
#                            year: 2022
#                            week:
#                            team: Wyoming
#                            game_id:
#                            athlete_id:
#                            stat_type_id:
#                            season_type:
#                            conference:
#                    get_play_types:
#                        filter_config:
#                    get_plays:
#                        filter_config:
#                            year: 2022
#                            week: 4
#                            season_type:
#                            team:
#                            offense:
#                            defense:
#                            conference:
#                            offense_conference:
#                            defense_conference:
#                            play_type:
#                            classification:
#        rankings:
#            api_class:
#                name: RankingsApi
#                api_methods:
#                    get_rankings:
#                        filter_config:
#                            year: 2022
#                            week:
#                            season_type:
#        ratings:
#            api_class:
#                name: RatingsApi
#                api_methods:
#                    get_conference_sp_ratings:
#                        filter_config:
#                            year: 2022
#                            conference:
#                    get_elo_ratings:
#                        filter_config:
#                            year: 2022
#                            week:
#                            team:
#                            conference:
#                    get_sp_ratings:
#                        filter_config:
#                            year: 2022
#                            team:
#                    get_srs_ratings:
#                        filter_config:
#                            year: 2022
#                            team:
#                            conference:
        recruiting:
            api_class:
                name: RecruitingApi
                api_methods:
#                    get_recruiting_groups:
#                        filter_config:
#                            start_year: 2013
#                            end_year: 2022
#                            #team: Wyoming
#                            conference:
                    get_recruiting_players:
                        filter_config:
                            year:
                            classification:
                            position:
                            state:
                            #team: Wyoming
#                    get_recruiting_teams:
#                        filter_config:
#                            year: 2022
#                            #team: Wyoming
#        stats:
#            api_class:
#                name: StatsApi
#                api_methods:
#                    get_advanced_team_game_stats:
#                        filter_config:
#                            year: 2022
#                            week: 4
#                            team:
#                            opponent:
#                            exclude_garbage_time:
#                            season_type:
#                    get_advanced_team_season_stats:
#                        filter_config:
#                            team: Wyoming
#                            exclude_garbage_time:
#                            start_week: 3
#                            end_week: 5
#                    #get_stat_categories - requires code fix to change to str value returned from API:
#                    #    filter_config:
#                    get_team_season_stats:
#                        filter_config:
#                            year: 2022
#                            team: Wyoming
#                            conference:
#                            start_week:
#                            end_week:
#        teams:
#            api_class:
#                name: TeamsApi
#                api_methods:
#                    get_fbs_teams:
#                        filter_config:
#                            year: 2022
#                    get_roster:
#                        filter_config:
#                            team:
#                            year: 2022
#                    get_talent:
#                        filter_config:
#                            year: 2022
#                   # get_team_matchup - pending code fix for support:
#                   #     filter_config:
#                   #         team1: UNLV
#                   #         team2: Wyoming
#                   #         min_year: 2020
#                   #         max_year: 2022
#                    get_teams:
#                        filter_config:
#                            conference: MWC
#        venues:
#            api_class:
#                name: VenuesApi
#                api_methods:
#                    get_venues:
#                        filter_config: