ingestion_configs:
    api_type:
        betting:
            api_class:
                name: BettingApi
                api_methods:
                    get_lines:
                        filter_configs:
                            game_id:
                            year:
                            week:
                            season_type:
                            team:
                            home:
                            away:
                            conference:
        coaches:
            api_class:
                name: CoachesApi
                api_methods:
                    get_coaches:
                        filter_configs:
                            first_name:
                            last_name:
                            team:
                            year:
                            min_year:
                            max_year:
        conferences:
           api_class:
               name: ConferencesApi
               api_methods:
                    get_conferences:
                        filter_configs:
        games:
            api_class:
                name: GamesApi
                api_methods:
                    get_advanced_box_score:
                        filter_configs:
                            game_id:
                    get_calendar:
                        filter_configs:
                            year:
                    get_game_media:
                        filter_configs:
                            year:
                            week:
                            season_type:
                            team:
                            conference:
                            media_type:
                            classification:
                    get_game_weather:
                        filter_configs:
                            game_id:
                            year:
                            week:
                            season_type:
                            team:
                            conference:
                            classification:
                    get_games:
                        filter_configs:
                            year:
                            week:
                            season_type:
                            team:
                            home:
                            away:
                            conference:
                            division:
                            id:
                    get_player_game_stats:
                        filter_configs:
                            year:
                            week:
                            season_type:
                            team:
                            conference:
                            category:
                            game_id:
                    get_scoreboard:
                        filter_configs:
                            classification:
                            conference:
                    get_team_game_stats:
                        filter_configs:
                            year:
                            week:
                            season_type:
                            team:
                            conference:
                            game_id:
                            classification:
                    get_team_records:
                        filter_configs:
                            year:
                            team:
                            conference:
        metrics:
            api_class:
                name: MetricsApi
                api_methods:
                    get_game_ppa:
                        filter_configs:
                            year:
                            week:
                            team:
                            conference:
                            exclude_garbage_time:
                            season_type:
                    get_player_game_ppa:
                        filter_configs:
                            year:
                            week:
                            team:
                            position:
                            player_id:
                            threshold:
                            exclude_garbage_time:
                            season_type:
                    get_player_season_ppa:
                        filter_configs:
                            year:
                            team:
                            conference:
                            position:
                            player_id:
                            threshold:
                            exclude_garbage_time:
                    get_predicted_points:
                        filter_configs:
                            down:
                            distance:
                    get_pregame_win_probabilities:
                        filter_configs:
                            year:
                            week:
                            team:
                            season_type:
                    get_team_ppa:
                        filter_configs:
                            year:
                            team:
                            conference:
                            exclude_garbage_time:
                    get_win_probability_data:
                        filter_configs:
                            game_id:
        players:
            api_class:
                name: PlayersApi
                api_methods:
                    get_player_season_stats:
                        filter_configs:
                            year:
                            team:
                            conference:
                            start_week:
                            end_week:
                            season_type:
                            category:
                    get_player_usage:
                        filter_configs:
                            year:
                            team:
                            conference:
                            position:
                            player_id:
                            exclude_garbage_time:
                    get_returning_production:
                        filter_configs:
                            year:
                            team:
                            conference:
                    get_transfer_portal:
                        filter_configs:
                            year:
                    player_search:
                        filter_configs:
                            search_term:
                            position:
                            team:
                            year:
        plays:
            api_class:
                name: PlaysApi
                api_methods:
                    get_live_plays:
                        filter_configs:
                            id:
                    get_play_stat_types:
                        filter_configs:
                    get_play_stats:
                        filter_configs:
                            year:
                            week:
                            team:
                            game_id:
                            athlete_id:
                            stat_type_id:
                            season_type:
                            conference:
                    get_play_types:
                        filter_configs:
                    get_plays:
                        filter_configs:
                            year:
                            week:
                            season_type:
                            team:
                            offense:
                            defense:
                            conference:
                            offense_conference:
                            defense_conference:
                            play_type:
                            classification:
        rankings:
            api_class:
                name: RankingsApi
                api_methods:
                    get_rankings:
                        filter_configs:
                            year:
                            week:
                            season_type:
        ratings:
            api_class:
                name: RatingsApi
                api_methods:
                    get_conference_sp_ratings:
                        filter_configs:
                            year:
                            conference:
                    get_elo_ratings:
                        filter_configs:
                            year:
                            week:
                            team:
                            conference:
                    get_sp_ratings:
                        filter_configs:
                            year:
                            team:
                    get_srs_ratings:
                        filter_configs:
                            year:
                            team:
                            conference:
        recruiting:
            api_class:
                name: RecruitingApi
                api_methods:
                    get_recruiting_groups:
                        filter_config:
                            #start_year: 2012
                            #end_year: 2022
                            #team: Wyoming
                            conference:
                    get_recruiting_players:
                        filter_config:
                            #year: 2022
                            classification:
                            position:
                            state:
                            #team: Wyoming
                    get_recruiting_teams:
                        filter_config:
                            #year: 2022
                            #team: Wyoming
        stats:
            api_class:
                name: StatsApi
                api_methods:
                    get_advanced_team_game_stats:
                        filter_configs:
                            year:
                            week:
                            team:
                            opponent:
                            exclude_garbage_time:
                            season_type:
                    get_advanced_team_season_stats:
                        filter_configs:
                            team:
                            exclude_garbage_time:
                            start_week:
                            end_week:
                    get_stat_categories:
                        filter_configs:
                    get_team_season_stats:
                        filter_configs:
                            year:
                            team:
                            conference:
                            start_week:
                            end_week:
        teams:
            api_class:
                name: TeamsApi
                api_methods:
                    get_fbs_teams:
                        filter_configs:
                            year:
                    get_roster:
                        filter_configs:
                            team:
                            year:
                    get_talent:
                        filter_configs:
                            year:
                    get_team_matchup:
                        filter_configs:
                            team1:
                            team2:
                            min_year:
                            max_year:
                    get_teams:
                        filter_configs:
                            conference:
        venues:
            api_class:
                name: VenuesApi
                api_methods:
                    get_venues:
                        filter_configs: